"""add category to chunks

Revision ID: b4fa4c521864
Revises: b9bfe6e5419c
Create Date: 2026-08-08 20:33:22.543410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4fa4c521864'
down_revision: Union[str, Sequence[str], None] = 'b9bfe6e5419c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('category', sa.String(length=20), server_default='writing', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'category')
    # ### end Alembic commands ###
